USE [master]
GO

/****** Object:  Database [HealthcareDB]    Script Date: 2/14/2019 5:42:19 PM ******/
CREATE DATABASE [HealthcareDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HealthcareDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HealthcareDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HealthcareDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HealthcareDB_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [HealthcareDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HealthcareDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HealthcareDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HealthcareDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HealthcareDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HealthcareDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HealthcareDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HealthcareDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HealthcareDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HealthcareDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HealthcareDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HealthcareDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HealthcareDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HealthcareDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HealthcareDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HealthcareDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HealthcareDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HealthcareDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HealthcareDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HealthcareDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HealthcareDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HealthcareDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HealthcareDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HealthcareDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HealthcareDB] SET RECOVERY FULL 
GO

ALTER DATABASE [HealthcareDB] SET  MULTI_USER 
GO

ALTER DATABASE [HealthcareDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HealthcareDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HealthcareDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HealthcareDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HealthcareDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HealthcareDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HealthcareDB] SET  READ_WRITE 
GO


